### ISSUE TITLE
AST Generation in Goyacc Calculator Example and Yacc Question

### ISSUE THREAD

**Issue by LazarenkoA** [slrtbtfs/goyacc-tutorial#1]
Hello, I'm trying your example from https://github.com/slrtbtfs/goyacc-tutorial/tree/master/ast_calculator. When I input "2+2*2" in the console, I get the error "syntax error: unexpected $unk," even though the AST seems to be built successfully when I inspect it in the debugger.

I also have several questions regarding yacc itself (apologies if they seem trivial):

Why is "yylex" used here: https://github.com/slrtbtfs/goyacc-tutorial/blob/master/ast_calculator/grammar.y#L19? Is it a reserved name, or can I manage it in some way?

**Comment by slrtbtfs** [comment]
Hi,

nice to see that someone is still testing this four years later!





> Hello, I'm trying your example from https://github.com/slrtbtfs/goyacc-tutorial/tree/master/ast_calculator. When I input "2+2*2" in the console, I get the error "syntax error: unexpected $unk," even though the AST seems to be built successfully when I inspect it in the debugger.

Any chance you are using this on Windows?

https://github.com/slrtbtfs/goyacc-tutorial/blob/1222cf0b47c757a25d51a026302a3fc97cc76981/ast_calculator/calculator.go#L20

This seems to assume that pressing the enter key after entering an expression will produce a `\n` line break while windows uses `\r\n` linebreaks. So the unrecognized character would be the `\r`. A PR to fix this behaviour would be welcome :)   


> 
> I also have several questions regarding yacc itself (apologies if they seem trivial):
> 
> Why is "yylex" used here: https://github.com/slrtbtfs/goyacc-tutorial/blob/master/ast_calculator/grammar.y#L19? Is it a reserved name, or can I manage it in some way?

Regarding the `yylex` variable: The generated parser code is placed in the `yyParserImpl.Parse` function in `y.go` inside that function the go code snippets defined in the grammar are basically placed between a bunch of gotos that implement a state machine. Inside the arguments of that function the variable yylex is used and in this case just directly accessed bypassing some of the abstraction of yacc. So the same code shows up again here, where the surrounding scope has `yylex` defined as a variable: https://github.com/slrtbtfs/goyacc-tutorial/blob/1222cf0b47c757a25d51a026302a3fc97cc76981/ast_calculator/y.go#L449-L452

**Comment by LazarenkoA** [comment]
> This seems to assume that pressing the enter key after entering an expression will produce a \n line break while windows uses \r\n linebreaks. So the unrecognized character would be the \r. A PR to fix this behaviour would be welcome :)

yes, I use Windows, thank you
